# Dependabot configuration for Nocturne project
version: 2
updates:
  # Python dependencies (backend)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    target-branch: "main"
    reviewers:
      - "nyasuto"
    labels:
      - "dependencies"
      - "python"
      - "backend"
    commit-message:
      prefix: "deps(backend)"
      prefix-development: "deps(backend/dev)"
      include: "scope"

  # Node.js dependencies (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    target-branch: "main"
    reviewers:
      - "nyasuto"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    commit-message:
      prefix: "deps(frontend)"
      prefix-development: "deps(frontend/dev)"
      include: "scope"
    # Skip major version updates for React and Next.js for stability
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: 1
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    target-branch: "main"
    reviewers:
      - "nyasuto"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    commit-message:
      prefix: "deps(ci)"
      include: "scope"