name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Allow conventional commit types
        types: |
          feat
          fix
          docs
          style
          refactor
          test
          chore
          ci
          build
          perf
        requireScope: false
        subjectPattern: ^[A-Z].{4,}$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          starts with an uppercase character and is at least 5 characters long.

  auto-merge-dependabot:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    needs: [pr-validation]
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Enable auto-merge for Dependabot PRs
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ github.event.pull_request.number }}
        merge-method: squash

  size-check:
    name: PR Size Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check PR size
      uses: microsoft/PR-SizeCheck@v1.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        maximum-size: 1000
        warning-size: 500
        exclude-files: |
          package-lock.json
          *.md
          *.yml
          *.yaml